kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "stresser" 
spec:
  source: 
    type: "Git"
    git:
      uri: "https://github.com/gshefer/CMapps"
    dockerfile: "apps/stresser"
  strategy: 
    type: "Source"
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "stresser:latest"
  output: 
    to:
      kind: "ImageStreamTag"
      name: "stresser:latest"