apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: stresser
  name: stresser
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: stresser
    spec:
      containers:
      - name: stresser
        image: stresser:latest
        ports:
            - containerPort: 8080
              protocol: "TCP"